
function r = copyTrackerToProject(this, trackerId, targetProjectId)
data = struct(...
    'project'    ,  ['/project/' num2str(targetProjectId)], ...
    'type'       ,  'TrackerReference', ...
    'name'       ,  'Music Player ProgCopy', ...
    'keyName'    ,  '', ...
    'description',  'Testing programmatic copy.', ...
    'descFormat' ,  'Wiki', ...
    'workflow'   ,  true);
r = webwrite([this.url '/rest/tracker/' num2str(trackerId) '/clone'], data, this.jsonOptions);
end
